import Foundation

/// Defense-in-depth check that auto-denies file tool requests targeting sensitive paths.
///
/// This runs in the approval server *before* publishing requests to the UI.
/// It is a heuristic layer — the primary enforcement is the CLI's `--disallowedTools`
/// rules generated by `CLIEngine.sensitivePathDenyRules()`. This catch exists for
/// cases where a tool bypasses CLI-level enforcement (e.g. `Write`, `Edit` which
/// aren't in the scoped allow list but may arrive via user approval flow).
///
/// This intentionally does NOT sniff Bash commands — that approach is trivially
/// bypassable and gives false confidence.
public enum SensitivePathPolicy {
    /// File tools whose path arguments are checked against the sensitive path list.
    private static let fileTools: Set<String> = [
        "Read", "Glob", "Grep", "Write", "Edit", "MultiEdit", "NotebookEdit",
    ]

    /// JSON keys that may contain file paths in tool input.
    private static let pathKeys = ["file_path", "path", "pattern", "directory"]

    /// Returns a denial reason if the request targets a sensitive path, or `nil` if allowed.
    public static func denyReason(for request: ApprovalRequest) -> String? {
        guard fileTools.contains(request.toolName) else { return nil }

        guard let data = request.inputJSON.data(using: .utf8),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return nil
        }

        let home = CLIDiscovery.realHomeDirectory

        for key in pathKeys {
            guard let rawPath = json[key] as? String, !rawPath.isEmpty else { continue }
            let normalized = URL(fileURLWithPath: rawPath).standardizedFileURL.path

            // Check home-relative sensitive paths
            for relativePath in CLIEngine.sensitiveRelativePaths {
                let pattern = "\(home)/\(relativePath)"
                if matchesSensitivePattern(path: normalized, pattern: pattern) {
                    return "Access denied: \(rawPath) is in a protected location."
                }
            }

            // Check global patterns (e.g. *.keychain-db)
            for pattern in CLIEngine.sensitiveGlobalPatterns {
                if matchesGlobalPattern(path: normalized, pattern: pattern) {
                    return "Access denied: \(rawPath) is a protected file type."
                }
            }
        }

        return nil
    }

    /// Matches a normalized path against a sensitive pattern that may end with `*`.
    private static func matchesSensitivePattern(path: String, pattern: String) -> Bool {
        if pattern.hasSuffix("*") {
            let prefix = String(pattern.dropLast())
            return path.hasPrefix(prefix)
        }
        return path == pattern
    }

    /// Matches a normalized path against a global suffix pattern like `*.keychain-db`.
    private static func matchesGlobalPattern(path: String, pattern: String) -> Bool {
        if pattern.hasPrefix("*") {
            let suffix = String(pattern.dropFirst())
            return path.hasSuffix(suffix)
        }
        return path == pattern
    }
}
